AllCops:
  Include:
    - '**/Rakefile'
    - 'lib/**/*.rb'
  Exclude:
    - 'Gemfile'
    - 'bin/**/*'
  TargetRubyVersion: 2.4

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/IfUnlessModifier:
  Enabled: false
